# Generated by Django 5.0.6 on 2024-08-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
