# Generated by Django 5.0.6 on 2024-08-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_chatroom_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='url',
        ),
        migrations.AddField(
            model_name='message',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
